### ISSUE TITLE
Problem with evalString

### ISSUE THREAD

**Issue by shudac** [zopefoundation/z3c.rml#10]
In an element: //document/template/pageTemplate/pageGraphic/drawRightString I have following snippet:

Page <evalString default="XXX"><pageNumber />-<getName id="pageZero" default="0" /></evalString> of <evalString default="XXX"><getName id="lastPageNo" default="999" />-<getName id="pageZero" default="0" /></evalString>

This causes code to error in special.py file at do_eval function. I found out that the value argument passed to the do_eval function contains string: "2-1 of" which does not evaluate. If I remove "of" from XML snippet, everything works correctly and passed value is: "2-1" which evaluates OK.

Correct value passed to the do_eval function in special.py should be the one encapsulated in evalString tag pair, nothing beyond that.

**Comment by strichter** [comment]
Fix merged.
