### ISSUE TITLE
How to render example rml

### ISSUE THREAD

**Issue by CelestialGuru** [zopefoundation/z3c.rml#107]
I dowloaded an example rml file from https://www.reportlab.com/extra/docs/rml-samples/. Specifically [test_000_complex.rml](https://www.reportlab.com/examples/rml/test/test_000_complex.rml). When attempting to compile it, the resulting pdf looks nothing like it's supposed to.

### What I did:

# Start a clean python environment:

```shell
docker run -it --rm python:3.11 bash
```

# Install z3c.rml

```shell
pip install z3c.rml=="4.2.1"
```

# Download example rml file

```shell
curl https://www.reportlab.com/examples/rml/test/test_000_complex.rml -o test_000_complex.rml
```

# Attempt to compile rml file

```bash
rml2pdf test_000_complex.rml
```

While running it outputs
```
Directive 'catchForms' could not be processed and was ignored. (file test_000_complex.rml, line 28)
Directive 'doForm' could not be processed and was ignored. (file test_000_complex.rml, line 29)
Directive 'pageGraphics' could not be processed and was ignored. (file test_000_complex.rml, line 33)
Directive 'doForm' could not be processed and was ignored. (file test_000_complex.rml, line 60)
Directive 'pageGraphics' could not be processed and was ignored. (file test_000_complex.rml, line 64)
```

It does in fact generate test_000_complex.pdf for what it's worth.

### What I expect to happen:

It should look like this: [test_000_complex.pdf](https://www.reportlab.com/examples/rml/test/test_000_complex.pdf)

### What actually happened:

It looked like this: [my_test_000_complex.pdf](https://github.com/zopefoundation/z3c.rml/files/10762669/test_000_complex.pdf)

### What version of Python and Zope/Addons I am using:

OS: I used docker to make it more repeatable, but for what it's worth the container is running `Debian GNU/Linux 11 (bullseye)`
Python version: 3.11.1
Packages installed:
```
# pip freeze
deprecation==2.1.0
lxml==4.9.2
packaging==23.0
pikepdf==7.0.0
Pillow==9.4.0
Pygments==2.14.0
reportlab==3.6.12
z3c.rml==4.2.1
zope.event==4.6
zope.interface==5.5.2
zope.schema==7.0.1
```
I do not know what Zope is.

### What I tried

The error message about `Directive ... could not be processed and was ignored` makes me think the program is not loading `rml.dtd` correctly.

I tried a few ways to define the top line in my file:

* `<!DOCTYPE document SYSTEM "rml.dtd">`
* `<!DOCTYPE document SYSTEM "../rml.dtd">`
* `<!DOCTYPE document SYSTEM "usr/local/lib/python3.11/site-packages/z3c/rml/rml.dtd">`
* `<!DOCTYPE document SYSTEM "/usr/local/lib/python3.11/site-packages/z3c/rml/rml.dtd">`

None of those changed the error message.

**Comment by regebro** [comment]
catchForms requires PageCatcher, which is a ReportLab commercial product and there is no Open Source alternative, so we can't implement it, unfortunately.
