### ISSUE TITLE
useCropMarks or cropMarks doesn't change pdf box dimensions

### ISSUE THREAD

**Issue by abhishiv** [zopefoundation/z3c.rml#12]
```
  <docinit useCropMarks="1">
```

This produces a document with visible crop marks and bleed. However inspecting the document in acrobat reveals that the all boxes have the same size. If I am not wrong, this code should make the make trimbox < mediabox by 36pt on all sides - 36pt is the default for this attribute.

Here's the [test pdf](http://pshop-public.herokuapp.com/3e698c33-fd24-4c7e-bd1b-32bffd3449e1.pdf), it can be inspected in acrobat by "Set Page Boxes" in toolset.

**Comment by strichter** [comment]
No response. It is also an upstream issue with Reportlab so needs to be reported there.
