### ISSUE TITLE
pageSize attribute of <template> tag

### ISSUE THREAD

**Issue by marcinn** [zopefoundation/z3c.rml#13]
Hey,

I spent hours trying switch to "a4 landscape" page using z3c.rml and I finally found that IPageTemplate contains "pagesize" attribute definition instead of "pageSize". Take a look at https://github.com/zopefoundation/z3c.rml/blob/master/src/z3c/rml/template.py#L161

Ok, changing attr name fixes my problem, but:
  * most of (?) attribute names are created with camel case notation
  * examples of RML (from ReportLab) contains pageSize attribute (http://www.reportlab.com/examples/rml/test/test_007_forms.rml)
  * RML DTD contains pageSize attribute (http://www.reportlab.com/docs/rml.dtd)

**Comment by strichter** [comment]
I am closing, since documentation is there.

**Comment by tejasshahu** [comment]
Thank you so much @strichter. Your comments resolved my issue.

**Comment by rapto** [comment]
The file is now in rst, not txt: https://github.com/zopefoundation/z3c.rml/blob/master/RML-DIFFERENCES.rst#incompatibilies
