### ISSUE TITLE
Are there any remaining blockers for Python 3 support?

### ISSUE THREAD

**Issue by kylemacfarlane** [zopefoundation/z3c.rml#23]
A blocker with Python 3 for me was lack of ReportLab but that's solved now with ReportLab 3.0 which is meant to be API compatible.

What's needed to make z3c.rml compatible with Python 3 beyond making sure everything works with ReportLab 3.0?

I checked the immediate dependencies and they all seem OK except maybe svg2rlg which is ancient but probably easily fixable.

**Comment by kylemacfarlane** [comment]
Should have full 2.7, 3.3, and 3.4 support now with PR #27.

**Comment by strichter** [comment]
Python 3 support merged into master and about to be released.
