### ISSUE TITLE
RML <drawing module> tag

### ISSUE THREAD

**Issue by carlskii** [zopefoundation/z3c.rml#25]
Hi is the <drawing module> tag supported in RML ? e.g.

```
<drawing module="test_014_scatterplot" function="ScatterPlotDrawing">
```

This seems to get ignored when I try it - it works if I use the commercial library though.

UPDATE

OK I see there's the <plugInGraphic> tag which seems to be what I need and I can get it to work using the "rml-examples-037-plugingraphic.rml" example. However, I'm struggling to make it work with anything else. Is there any chance you can provide a simple example of rendering a dynamically created pie chart into a document please. 

Carl

**Comment by strichter** [comment]
The documentation says this about the `drawing` directive:

```
- ``<drawing>``: There is no documentation for this tag and I do not know what
  it is supposed to do. Thus z3c.rml does not implement it.
```

If you can describe the behavior and what it does, I can have a look.
