### ISSUE TITLE
Python 2.6

### ISSUE THREAD

**Issue by esledov** [zopefoundation/z3c.rml#29]
Is the latest version of z3c.rml (2.7.2) supposed to work with python 2.6?
(Required reporlab 3.0 library has no python 2.6 support).

It changes history it says "Updated code to work with ReportLab 3.x".  But it does not mention that previous versions of Reportlab and python 2.6 are not supported.

Could you clarify it please?

**Comment by FelixSchwarz** [comment]
I guess that's fixed in 9895c7ed (dropping support for Python 2.6)

**Comment by strichter** [comment]
Yeah, no Python 2.6 support. See setup.py.
