### ISSUE TITLE
Error with latest version of report lab and ParaParser

### ISSUE THREAD

**Issue by skeltel** [zopefoundation/z3c.rml#30]
The latest version of reportlab has changed the ParaParser class to use a tag parameter that is not optional. In the module z3c.rml.paraparser line 144 needs to be changed from self._pop() to something with a parameter. On my side it works with self._pop('para') but not sure that is the correct change as I do not know the package very well.

Thanks

**Comment by kylemacfarlane** [comment]
I fixed this and a bunch of others issues with 3.1.44 over in #27.

**Comment by strichter** [comment]
#27 has been merged.
