### ISSUE TITLE
svg2rlg.py fails under Python3

### ISSUE THREAD

**Issue by trvrm** [zopefoundation/z3c.rml#42]
I ran into a couple of cases where `svg2rlg.Renderer.render` fails with

> object of type 'map' has no len()

Converting map objects to lists in about 5 places resolved the problem, e.g.:

```
points = map(parseLength, re.split('[ ,]+', points))
```

becomes

```
points = list(map(parseLength, re.split('[ ,]+', points)))
```

I can put together a pull request if you like.

**Comment by strichter** [comment]
Please do.
