### ISSUE TITLE
Dynamic Table Height

### ISSUE THREAD

**Issue by PabloVallejo** [zopefoundation/z3c.rml#43]
Hi, 

Frames have to have the height attribute by default, is there a way of specifying a dynamic height so that I can render a table with a dynamic number of rows?

Thanks,

```xml
<!-- Frame definition has to have height -->
<frame id="start" x1="1in" y1="6.69in" width="6.27in" height="3in"/>
```

**Comment by strichter** [comment]
You should use a templating language for that, but platypus does not provide for dynaic frames, so there is no need to support them in z3c.rml.

For example, I use zope.pagetemplate for generating all my RML.

**Comment by PabloVallejo** [comment]
@strichter thanks, 

I'm going to try with Django templating system as the project is setup in this framework.

👍
