### ISSUE TITLE
UTF-8 Encoding not fully supported

### ISSUE THREAD

**Issue by PabloVallejo** [zopefoundation/z3c.rml#44]
I'm generating a report, and my problem is that RML is not properly rendering the following characters:

> Ó, Í

![screen shot 2016-06-24 at 8 49 45 am](https://cloud.githubusercontent.com/assets/1751074/16339519/b715b97e-39e8-11e6-9aca-6b93e1149f4f.png)

Any pointers on this issue? 
Thanks
#### Setup

``` xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
```
- Pyton 3
- Django 1.9.6

**Comment by kylemacfarlane** [comment]
This is a problem with the font you're using rather than z3c.rml. You need to register a font which supports the characters you need.
