### ISSUE TITLE
index tag is not implemented?

### ISSUE THREAD

**Issue by goocy** [zopefoundation/z3c.rml#53]
\<showIndex\> is listed in the documentation, but apparently \<index\> doesn't work at all. It's also not in the list of missing features.

**Comment by strichter** [comment]
This is not true. See the [Index Tag Test RML](https://github.com/zopefoundation/z3c.rml/blob/master/src/z3c/rml/tests/input/tag-index.rml) and resulting [PDF](https://github.com/zopefoundation/z3c.rml/raw/master/src/z3c/rml/tests/expected/tag-index.pdf)
