### ISSUE TITLE
Make processing observable

### ISSUE THREAD

**Issue by marcinn** [zopefoundation/z3c.rml#57]
Adding observable pattern to directives.RMLDirective, document.Document and maybe rml2pdf.parseString would be nice improvement allowing to monitor progress of documents generation process.

This may be achieved with `pyobservable`.

**Comment by strichter** [comment]
Note that rendering the PDF takes by far the most time. So you really need support for observables in Reportlab. I am closing this issue since z3c.rml is not the right layer. Once Reportlab supports observable, then we can revisit the topic here.
