### ISSUE TITLE
Dynamically passing images to the RML

### ISSUE THREAD

**Issue by wswld** [zopefoundation/z3c.rml#61]
Is there a way to pass an image to the final PDF without using the disc? I generate a graph w/ `matplotlib` since `z3c.rml` doesn't have a way of generating a scatter plot through drawing (there is no support for drawing tag) and it seems there is no way to pass the generated file directly.

**Comment by wswld** [comment]
It seems that the only way to acheive that is to pass base64-encoded image to `src` attribute of the `img` tag, right?

**Comment by strichter** [comment]
Yes, that's what we are using. Of course, there is drawing support but that will not help you with your graph. Native PS support would be nice, but I have no motivation or need to implement that.

**Comment by strichter** [comment]
The solution for this is really the ``<drawing>`` directive. But since it is not documented and I do not know which underlying Reportlab classes it uses, it is documented as not implemented.
