### ISSUE TITLE
Is this package compatible with current Zope 2/4/5?

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/z3c.rml#69]
One of the apps I maintain (currently Zope 2, soon Zope 4) uses a "forked/vendored" version of  https://github.com/romanlv/trml2pdf which I would like to replace with z3c.rml to make the transition to Zope 4 / Python 3 smoother.

Is this package compatible with Zope 2/4/5?

If yes, the meta data for PyPi should be updated:

Currently:
`classifier  keywords="zope3 rml reportlab pdf pagetemplate",`

**Comment by regebro** [comment]
It should be. The zope3 label there is not about versions, but more about that it's built with that technology stack, ie zope.interfaces et al, but it exist in the Zope 2 world as well, and I'm not aware of any specific version requirements there. It's absolutely true that the zope3 label there is outdated and serves no purpose any more.

**Comment by jugmac00** [comment]
@regebro Thank you very much for your answer.

@icemac What labels would you suggest?

**Comment by icemac** [comment]
@jugmac00 I'd suggest to keep the `Zope :: 3` label as it hints about the technologie used in the package. If it is usable in Zope 4 without modifications has to be evaluated separately.

**Comment by jugmac00** [comment]
Thank you!
