### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by Benjamin-fr** [zopefoundation/z3c.rml#72]
This code works :
> \<link destination="PICTURE_18">
>  \<para>18\</para>
>\</link>
> \<link destination="PICTURE_19">
>  \<para>19\</para>
>\</link>

But this does not :
> \<para>
> \<link destination="PICTURE_18">18\</link>
> \<link destination="PICTURE_19">19\</link>
> \</para>

In other words, it doesn't seem possible to have multiple links on the same line. Did I miss something ? Or is there an other way to do that ?

Thanks in advance.

**Comment by jugmac00** [comment]
Hi @Benjamin-fr 

thank you for the reported issue.

"does not work" is a bit vague.

Could you please elaborate whether you get wrong pdf output or an error message?

In case of the latter one, please provide the error message.

Thank you!

**Comment by Benjamin-fr** [comment]
Thank you for your reply,

Indeed, when no para tag is used inside link tag (second case), then pdf is generated, and mouse icon change to hand over the text, but when I click, a message box appear asking confirmation to access to an external link ( file:///D|PICTURE_19 ), as if destination attribute was interpreted as url attribute of the link tag.

**Comment by strichter** [comment]
`z3c.rml` does not processing inside the Paragraph, i.e. `<para>` tag. We support whatever Reportlab supports. And the API reference states that you are supposed to use `<a href="">Link</a>`.

Reportlab Reference: https://www.reportlab.com/docs/reportlab-reference.pdf

**Comment by Benjamin-fr** [comment]
Thank you @strichter 
`<a>` and '<link>' seem to have the same behavior, however I changed to `<a href=>` to conform the documentation. Finally my mistake was that I missed `#` before the anchor name in the href.

Problem solved !
