### ISSUE TITLE
getName not working inside pageTemplate/pageGraphics/place

### ISSUE THREAD

**Issue by shudac** [zopefoundation/z3c.rml#8]
With switch from z3c.rml 1.0.0. to 2.1.0 getName stopped working inside tag sequence //document/template/ageTemplate/pageGraphics/place

**Comment by strichter** [comment]
@shudac Wasn't this fixed with your merge request? If so, let's close the issue, since I merged that MR.

**Comment by strichter** [comment]
Closing due to no response.
