### ISSUE TITLE
How to generate the actual pdf??

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [zopefoundation/z3c.rml#80]
Any tuto as how to generate the pdf? The docs cover only syntax

**Comment by rapto** [comment]
```
from z3c.rml import rml2pdf
rml2pdf.go(xmlInputName, outputFileName)
```
See a complete example at https://blog.alec.id.au/adventure-into-reportlab-and-rml/

**Comment by Abdur-rahmaanJ** [comment]
@rapto that's a huge miss, thanks, submitting PR
