### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by tieugene** [zopefoundation/z3c.rml#87]
Compare with [original things](https://github.com/romanlv/trml2pdf/tree/master/examples) (source and reportlab's renders): 
[ex3.pdf](https://github.com/zopefoundation/z3c.rml/files/5796197/ex3.pdf)
[ex12.pdf](https://github.com/zopefoundation/z3c.rml/files/5796199/ex12.pdf)
And yet another examples, that not rendering at all: devis, ex5

**Comment by strichter** [comment]
The example 3 ellipsis are simply wrong in trml. They treat the `width` and `height` as `x2` and `y2`, respectively. If the commercial RML does this also incorrectly, I am more than happy to document that as an incompatibility.

**Comment by strichter** [comment]
So for example 12 I purposefully did break compatibility with RML because their interpretation made no sense. By default `<image>` does not preserve the aspect ratio. However, there is a `preserveAspectRatio` option that when set will get the trml output.
